name: Convert All SRS to TXT

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.2.0
        with:
          ref: rule-set

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

          # 获取最新的 sing-box 版本
          latest_version=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name)
          download_url="https://github.com/SagerNet/sing-box/releases/download/$latest_version/sing-box-${latest_version#v}-linux-amd64.tar.gz"

          # 下载并安装 sing-box
          curl -L -o sing-box.tar.gz "$download_url"
          tar -xzf sing-box.tar.gz  # 解压所有文件
          cd "sing-box-${latest_version#v}-linux-amd64"  # 进入解压目录
          chmod +x sing-box  # 确保可执行
          mv sing-box /usr/local/bin/  # 移动到可执行路径
          cd ..  # 返回上级目录

      - name: List files
        run: ls -l  # 列出当前目录的文件以进行调试

      - name: Convert SRS to TXT
        run: |
          chmod +x convert.sh
          ./convert.sh
