name: Convert All SRS to TXT

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 更新为 v3.2.0 或更高版本
        with:
          ref: rule-set  # 确保在 rule-set 分支上

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install jq

          # 获取最新的 sing-box 版本
          latest_version=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name)
          download_url="https://github.com/SagerNet/sing-box/releases/download/$latest_version/sing-box-${latest_version#v}-linux-amd64.tar.gz"

          # 下载并安装 sing-box
          curl -L -o sing-box.tar.gz "$download_url"
          tar -xzf sing-box.tar.gz
          chmod +x sing-box
          mv sing-box /usr/local/bin/

      - name: Convert SRS to TXT
        run: |
          chmod +x convert.sh
          ./convert.sh
