name: Convert All SRS to TXT

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: rule-set  # 确保在 rule-set 分支上

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install jq
          curl -L -o sing-box https://github.com/your-repo/sing-box/releases/latest/download/sing-box-linux-amd64
          chmod +x sing-box
          mv sing-box /usr/local/bin/

      - name: Convert SRS to TXT
        run: |
          chmod +x convert.sh
          ./convert.sh
