name: Convert SRS to TXT

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次（UTC 时间）
  workflow_dispatch:

jobs:
  convert-srs-to-txt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout rule-set branch
      uses: actions/checkout@v3
      with:
        ref: rule-set

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Download latest sing-box
      run: |
        latest_version=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name)
        download_url="https://github.com/SagerNet/sing-box/releases/download/$latest_version/sing-box-${latest_version#v}-linux-amd64.tar.gz"
        curl -L -o sing-box.tar.gz "$download_url"
        tar -zxvf sing-box.tar.gz
        chmod +x sing-box

    - name: Convert .srs files to .txt
      run: |
        # 创建转换输出的目录
        mkdir -p converted_txt
        for srs_file in *.srs; do
          # 临时 .json 文件名
          temp_output_file="temp_output.json"
          # 最终输出的 .txt 文件名
          final_output_file="converted_txt/${srs_file%.srs}.txt"

          # 使用 sing-box 进行转换
          ./sing-box rule-set decompile --output "$temp_output_file" "$srs_file"

          # 使用 jq 格式化输出
          jq -r '
            .rules[] |
            (.domain_suffix // empty | if type == "array" then .[] | "DOMAIN-SUFFIX, \(.)" else "DOMAIN-SUFFIX, \(.)" end) // empty,
            (.domain // empty | if type == "array" then .[] | "DOMAIN, \(.)" else "DOMAIN, \(.)" end) // empty
          ' "$temp_output_file" > "$final_output_file"

          # 清理临时 .json 文件
          rm "$temp_output_file"
        done

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add converted_txt/*.txt
        git commit -m "Convert .srs files to .txt"
        git push -f origin rule-set
