name: Convert All SRS to TXT

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main  # 检出 main 分支

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: List branches
        run: git branch -a  # 列出所有本地和远程分支

      - name: Delete existing rule-set branch
        run: |
          git fetch origin
          git branch -D rule-set || echo "rule-set branch does not exist"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

          # 获取最新的 sing-box 版本
          latest_version=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name)
          download_url="https://github.com/SagerNet/sing-box/releases/download/$latest_version/sing-box-${latest_version#v}-linux-amd64.tar.gz"

          # 下载并安装 sing-box
          curl -L -o sing-box.tar.gz "$download_url"
          tar -xzf sing-box.tar.gz  # 解压所有文件
          cd "sing-box-${latest_version#v}-linux-amd64"  # 进入解压目录
          chmod +x sing-box  # 确保可执行
          mv sing-box /usr/local/bin/  # 移动到可执行路径
          cd ..  # 返回上级目录

      - name: List files
        run: ls -l  # 列出当前目录的文件以进行调试

      - name: Make convert.sh executable
        run: chmod +x ./convert.sh  # 确保 convert.sh 可执行

      - name: Execute convert.sh
        run: ./convert.sh  # 执行脚本

      - name: Create rule-set branch if it doesn't exist
        run: |
          git checkout -b rule-set || git checkout rule-set  # 创建或切换到 rule-set 分支
          rm -rf *  # 删除当前目录下的所有文件和文件夹
          git config user.name "love796-QAQ"
          git config user.email "wangshuo523@outlook.com"

      - name: Commit and push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then  # 检查是否有变更
            git add .
            git commit -m "Update converted files"
            git pull origin rule-set --rebase  # 拉取远程更改并与本地更改合并
            git push origin rule-set
          else
            echo "No changes to commit."
          fi
